language: node_js
node_js: stable

install:
    - npm install hexo-cli -g
    - npm install

script:
    - hexo generate

after_script:
    - cd ./public
    - git init
    - git config user.name "tonny travis"
    - git config user.email "wodexintiao@gmail.com"
    - git add .
    - git commit -m 'update docs'
    - git push -f -q "https://${GITHUB_TOKEN}@${GITHUB_REF}" master:gh-pages

env:
    global:
        - GITHUB_REF: github.com/tonny-zhang/blog.git     
